active_plan: "Silent (fanless)"
plans:
  - name: "Silent (fanless)"
    plan: "silent"
    cpu_curve: "30c:0%,49c:0%,59c:0%,69c:0%,79c:31%,89c:49%,99c:56%,109c:56%"
    gpu_curve: "30c:0%,49c:0%,59c:0%,69c:0%,79c:34%,89c:51%,99c:61%,109c:61%"
  - name: "Silent (low-speed fan)"
    plan: "silent"
    cpu_curve: "30c:10%,49c:10%,59c:10%,69c:10%,79c:31%,89c:49%,99c:56%,109c:56%"
    gpu_curve: "30c:0%,49c:0%,59c:0%,69c:0%,79c:34%,89c:51%,99c:61%,109c:61%"
  - name: "Silent (default fan speed)"
    plan: "silent"
  - name: "Windows"
    plan: "windows"
  - name: "Performance"
    plan: "performance"
  - name: "Turbo"
    plan: "turbo"
